// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/http/request.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// HttpClient is a mock of Client interface
type HttpClient struct {
	ctrl     *gomock.Controller
	recorder *HttpClientMockRecorder
}

// HttpClientMockRecorder is the mock recorder for HttpClient
type HttpClientMockRecorder struct {
	mock *HttpClient
}

// NewHttpClient creates a new mock instance
func NewHttpClient(ctrl *gomock.Controller) *HttpClient {
	mock := &HttpClient{ctrl: ctrl}
	mock.recorder = &HttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *HttpClient) EXPECT() *HttpClientMockRecorder {
	return m.recorder
}

// Request mocks base method
func (m *HttpClient) Request(verb, endpoint string, body interface{}) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", verb, endpoint, body)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request
func (mr *HttpClientMockRecorder) Request(verb, endpoint, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*HttpClient)(nil).Request), verb, endpoint, body)
}

// PostRequest mocks base method
func (m *HttpClient) PostRequest(endpoint string, body interface{}) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostRequest", endpoint, body)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostRequest indicates an expected call of PostRequest
func (mr *HttpClientMockRecorder) PostRequest(endpoint, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostRequest", reflect.TypeOf((*HttpClient)(nil).PostRequest), endpoint, body)
}
