env: "test"

api:
  host: "http://dev.enchainte.com:80"
  endpoints:
    message_write: "/v1/messages"
    message_fetch: "/v1/messages/fetch"
    message_proof: "/v1/messages/proof"

cloud:
  azure:
    test: true
    host: "https://enchainte-config.azconfig.io"
    path_prod: "/kv?key=SDK_*&label=PROD"
    path_test: "/kv?key=SDK_*&label=TEST"